algoritmo "Missao Semana 3 - Cálculo do Salário "
// Função : Algoritmo que a partir de um salario informado pelo usuario,
// retorne o valor do mesmo com um aumento de 30%.
// Autor : Mauricio Herrera
// Data : 19/05/2022

var
SalarioEntrada,SalarioSaida: real
inicio
// Seção de Comandos 
Escreval("SalarioEntrada")
leia(salarioEntrada)
salarioSaida <- SalarioEntrada * 1.3
Escreval("SalarioSaida")// Salário con aumento de 30%
Escreval(salarioSaida)
fimalgoritmo
